local util = require("tweaker.util")
local palette = require("tweaker.palette")

--- Generates a standalone colorscheme from the current session's highlights (base
--- colorscheme + applied tweaker overrides), with every hex color hoisted into a
--- named palette variable (red_1, light_blue_2, ...) referenced by the set calls.
local M = {}

-- Hex-valued keys hoisted into palette vars, and pass-through gui attributes.
local HEX_KEYS = { "fg", "bg", "sp" }
local ATTRS = {
    "bold",
    "italic",
    "underline",
    "undercurl",
    "underdouble",
    "underdotted",
    "underdashed",
    "strikethrough",
    "reverse",
    "standout",
    "nocombine",
    "altfont",
    "blend",
}

--- Sort key for grouping palette variables by color name: (core family,
--- variant rank dark<base<light, hex-order index). Keeps all shades of a color
--- together and its dark_/base/light_ variants adjacent.
---@param v string  variable name like "dark_blue_2"
---@return string core, integer variant, integer index
local function name_key(v)
    local base, idx = v:match("^(.-)_(%d+)$")
    base = base or v
    idx = tonumber(idx) or 0
    local d = base:match("^dark_(.+)$")
    local l = base:match("^light_(.+)$")
    if d then
        return d, 0, idx
    elseif l then
        return l, 2, idx
    end
    return base, 1, idx
end

--- hex -> variable name. Hexes are grouped by nearest master color, and the
--- shades within each name are numbered (_1, _2, ...) by perceptual lightness
--- (dark -> light) so they read as a clean gradient.
---@return table map, string[] hexes
local function build_vars(used)
    local hexes = vim.tbl_keys(used)
    -- Group hexes by their nearest master color name.
    local by_name = {}
    for _, hex in ipairs(hexes) do
        local base = palette.nearest(hex)
        by_name[base] = by_name[base] or {}
        table.insert(by_name[base], hex)
    end
    -- Within each name, order by lightness and number _1 (darkest) upward.
    local map = {}
    for base, list in pairs(by_name) do
        table.sort(list, function(a, b)
            return palette.lightness(a) < palette.lightness(b)
        end)
        for i, hex in ipairs(list) do
            map[hex] = base .. "_" .. i
        end
    end
    return map, hexes
end

--- Build the colorscheme source text.
---@param name string  colorscheme name
---@return string
function M.generate(name)
    local groups = vim.api.nvim_get_hl(0, {})

    -- Collect used hex colors and the emittable groups.
    local used = {}
    local names = {}
    for gname, def in pairs(groups) do
        for _, k in ipairs(HEX_KEYS) do
            if type(def[k]) == "number" then
                used[util.hex(def[k])] = true
            end
        end
        names[#names + 1] = gname
    end
    table.sort(names)
    local var, sorted_hexes = build_vars(used)

    local out = {}
    local function add(line)
        out[#out + 1] = line
    end

    add("-- Generated by tweaker.nvim. Re-running :TweakerBake overwrites this file.")
    add('vim.cmd("highlight clear")')
    add(string.format("vim.g.colors_name = %q", name))
    add(string.format("vim.o.background = %q", vim.o.background))
    add("")

    -- Palette table, grouped by color name for readability: all shades of a
    -- color sit together (its dark_/base/light_ variants kept adjacent), and
    -- within a name the hex-order index (_1, _2, ...) is preserved.
    add("local p = {")
    local w = 0
    for _, hex in ipairs(sorted_hexes) do
        w = math.max(w, #var[hex])
    end
    local print_order = vim.deepcopy(sorted_hexes)
    table.sort(print_order, function(a, b)
        local ca, va, ia = name_key(var[a])
        local cb, vb, ib = name_key(var[b])
        if ca ~= cb then
            return ca < cb
        end
        if va ~= vb then
            return va < vb
        end
        return ia < ib
    end)
    for _, hex in ipairs(print_order) do
        add(string.format("  %-" .. w .. 's = "%s",', var[hex], hex))
    end
    add("}")
    add("")
    add("local set = vim.api.nvim_set_hl")

    -- One set() per group (sorted). fg/bg/sp reference palette vars.
    for _, gname in ipairs(names) do
        local def = groups[gname]
        local parts = {}
        if def.link then
            parts[#parts + 1] = string.format("link = %q", def.link)
        else
            for _, k in ipairs(HEX_KEYS) do
                if type(def[k]) == "number" then
                    parts[#parts + 1] = k .. " = p." .. var[util.hex(def[k])]
                end
            end
            for _, k in ipairs(ATTRS) do
                if def[k] ~= nil then
                    parts[#parts + 1] = k .. " = " .. tostring(def[k])
                end
            end
        end
        if #parts > 0 then
            add(string.format("set(0, %q, { %s })", gname, table.concat(parts, ", ")))
        end
    end

    return table.concat(out, "\n") .. "\n"
end

--- Write the generated colorscheme to stdpath("config")/colors/<name>.lua.
--- Refuses to overwrite an existing file unless `force` is true.
---@param name string
---@param force boolean|nil
function M.write(name, force)
    if not name or name == "" then
        name = (vim.g.colors_name or "tweaker") .. "-tweaked"
    end
    local dir = vim.fn.stdpath("config") .. "/colors"
    local path = dir .. "/" .. name .. ".lua"
    if not force and vim.uv.fs_stat(path) then
        vim.notify(("tweaker: %s exists — use :TweakerBake! %s to overwrite"):format(path, name), vim.log.levels.WARN)
        return
    end
    vim.fn.mkdir(dir, "p")
    local f = io.open(path, "w")
    if not f then
        vim.notify("tweaker: cannot write " .. path, vim.log.levels.ERROR)
        return
    end
    f:write(M.generate(name))
    f:close()
    vim.notify(("tweaker: exported colorscheme to %s"):format(path), vim.log.levels.INFO)
    return path
end

return M
