local util = require("tweaker.util")
local palette = require("tweaker.palette")

--- Generates a standalone colorscheme from the current session's highlights (base
--- colorscheme + applied tweaker overrides), with every hex color hoisted into a
--- named palette variable (red_1, light_blue_2, ...) referenced by the set calls.
local M = {}

-- Hex-valued keys hoisted into palette vars, and pass-through gui attributes.
local HEX_KEYS = { "fg", "bg", "sp" }
local ATTRS = {
    "bold",
    "italic",
    "underline",
    "undercurl",
    "underdouble",
    "underdotted",
    "underdashed",
    "strikethrough",
    "reverse",
    "standout",
    "nocombine",
    "altfont",
    "blend",
}

--- hex -> variable name. Unique hexes are sorted by value, grouped by nearest
--- master color, and numbered (_1, _2, ...) in that hex order.
---@return table map, string[] sorted_hexes
local function build_vars(used)
    local hexes = vim.tbl_keys(used)
    table.sort(hexes, function(a, b)
        return palette.val(a) < palette.val(b)
    end)
    local counts, map = {}, {}
    for _, hex in ipairs(hexes) do
        local base = palette.nearest(hex)
        counts[base] = (counts[base] or 0) + 1
        map[hex] = base .. "_" .. counts[base]
    end
    return map, hexes
end

--- Build the colorscheme source text.
---@param name string  colorscheme name
---@return string
function M.generate(name)
    local groups = vim.api.nvim_get_hl(0, {})

    -- Collect used hex colors and the emittable groups.
    local used = {}
    local names = {}
    for gname, def in pairs(groups) do
        for _, k in ipairs(HEX_KEYS) do
            if type(def[k]) == "number" then
                used[util.hex(def[k])] = true
            end
        end
        names[#names + 1] = gname
    end
    table.sort(names)
    local var, sorted_hexes = build_vars(used)

    local out = {}
    local function add(line)
        out[#out + 1] = line
    end

    add("-- Generated by tweaker.nvim. Re-running :TweakerBake overwrites this file.")
    add('vim.cmd("highlight clear")')
    add(string.format("vim.g.colors_name = %q", name))
    add(string.format("vim.o.background = %q", vim.o.background))
    add("")

    -- Palette table, sorted by hex, aligned for readability.
    add("local p = {")
    local w = 0
    for _, hex in ipairs(sorted_hexes) do
        w = math.max(w, #var[hex])
    end
    for _, hex in ipairs(sorted_hexes) do
        add(string.format("  %-" .. w .. 's = "%s",', var[hex], hex))
    end
    add("}")
    add("")
    add("local set = vim.api.nvim_set_hl")

    -- One set() per group (sorted). fg/bg/sp reference palette vars.
    for _, gname in ipairs(names) do
        local def = groups[gname]
        local parts = {}
        if def.link then
            parts[#parts + 1] = string.format("link = %q", def.link)
        else
            for _, k in ipairs(HEX_KEYS) do
                if type(def[k]) == "number" then
                    parts[#parts + 1] = k .. " = p." .. var[util.hex(def[k])]
                end
            end
            for _, k in ipairs(ATTRS) do
                if def[k] ~= nil then
                    parts[#parts + 1] = k .. " = " .. tostring(def[k])
                end
            end
        end
        if #parts > 0 then
            add(string.format("set(0, %q, { %s })", gname, table.concat(parts, ", ")))
        end
    end

    return table.concat(out, "\n") .. "\n"
end

--- Write the generated colorscheme to stdpath("config")/colors/<name>.lua.
--- Refuses to overwrite an existing file unless `force` is true.
---@param name string
---@param force boolean|nil
function M.write(name, force)
    if not name or name == "" then
        name = (vim.g.colors_name or "tweaker") .. "-tweaked"
    end
    local dir = vim.fn.stdpath("config") .. "/colors"
    local path = dir .. "/" .. name .. ".lua"
    if not force and vim.uv.fs_stat(path) then
        vim.notify(("tweaker: %s exists — use :TweakerBake! %s to overwrite"):format(path, name), vim.log.levels.WARN)
        return
    end
    vim.fn.mkdir(dir, "p")
    local f = io.open(path, "w")
    if not f then
        vim.notify("tweaker: cannot write " .. path, vim.log.levels.ERROR)
        return
    end
    f:write(M.generate(name))
    f:close()
    vim.notify(("tweaker: exported colorscheme to %s"):format(path), vim.log.levels.INFO)
    return path
end

return M
