local util = require("tweaker.util")
local palette = require("tweaker.palette")

--- Generates a standalone colorscheme from the current session's highlights (base
--- colorscheme + applied tweaker overrides), with every hex color hoisted into a
--- named palette variable (red_1, light_blue_2, ...) referenced by the set calls.
local M = {}

-- Hex-valued keys hoisted into palette vars, and pass-through gui attributes.
local HEX_KEYS = { "fg", "bg", "sp" }
local ATTRS = {
    "bold",
    "italic",
    "underline",
    "undercurl",
    "underdouble",
    "underdotted",
    "underdashed",
    "strikethrough",
    "reverse",
    "standout",
    "nocombine",
    "altfont",
    "blend",
}

--- hex -> variable name, plus the hexes in final palette order. Hexes are
--- grouped by nearest color name; the groups are ordered into a gradient by
--- name_rank; and the shades within each name are numbered (_1, _2, ...) by
--- perceptual lightness (dark -> light).
---@return table map, string[] ordered
local function build_vars(used)
    local hexes = vim.tbl_keys(used)
    -- Group hexes by their nearest color name.
    local by_name = {}
    for _, hex in ipairs(hexes) do
        local name = palette.nearest(hex)
        by_name[name] = by_name[name] or {}
        table.insert(by_name[name], hex)
    end
    -- Emit names in gradient order; within each name, order by lightness.
    local names = vim.tbl_keys(by_name)
    table.sort(names, function(a, b)
        return palette.name_rank(a) < palette.name_rank(b)
    end)
    local map, ordered = {}, {}
    for _, name in ipairs(names) do
        local list = by_name[name]
        table.sort(list, function(a, b)
            return palette.lightness(a) < palette.lightness(b)
        end)
        for i, hex in ipairs(list) do
            map[hex] = name .. "_" .. i
            ordered[#ordered + 1] = hex
        end
    end
    return map, ordered
end

--- Build the colorscheme source text.
---@param name string  colorscheme name
---@return string
function M.generate(name)
    local groups = vim.api.nvim_get_hl(0, {})

    -- Collect used hex colors and the emittable groups.
    local used = {}
    local names = {}
    for gname, def in pairs(groups) do
        for _, k in ipairs(HEX_KEYS) do
            if type(def[k]) == "number" then
                used[util.hex(def[k])] = true
            end
        end
        names[#names + 1] = gname
    end
    table.sort(names)
    local var, ordered = build_vars(used)

    -- Which groups use each color (by hex), for the palette comments. Links
    -- carry no color of their own, so they never appear here. A group that uses
    -- the same color for more than one attribute is counted once.
    local usage = {}
    for _, gname in ipairs(names) do
        local def = groups[gname]
        if not def.link then
            local seen = {}
            for _, k in ipairs(HEX_KEYS) do
                if type(def[k]) == "number" then
                    local hx = util.hex(def[k])
                    if not seen[hx] then
                        seen[hx] = true
                        usage[hx] = usage[hx] or {}
                        usage[hx][#usage[hx] + 1] = gname
                    end
                end
            end
        end
    end

    local out = {}
    local function add(line)
        out[#out + 1] = line
    end

    -- The upstream colorscheme this was baked from. When re-baking a scheme we're
    -- already on, carry its original base forward instead of chaining names.
    local base = (vim.g.tweaker_baked == vim.g.colors_name and vim.g.tweaker_baked_base)
        or vim.g.colors_name
        or "(unknown)"
    add(string.format("-- Generated by tweaker.nvim from the %q colorscheme.", base))
    add("--")
    add(string.format("-- While %q is your active colorscheme, :TweakerBake re-bakes your latest", name))
    add("-- tweaks back into THIS file and keeps you on it. Under a different colorscheme,")
    add('-- :TweakerBake writes a separate "<active>-tweaked" file (and needs the ! bang to')
    add("-- overwrite an existing one).")
    add('vim.cmd("highlight clear")')
    add(string.format("vim.g.colors_name = %q", name))
    -- Markers so a later :TweakerBake recognizes this as a tweaker scheme and
    -- re-bakes in place (see M.write).
    add(string.format("vim.g.tweaker_baked = %q", name))
    add(string.format("vim.g.tweaker_baked_base = %q", base))
    add(string.format("vim.o.background = %q", vim.o.background))
    add("")

    -- Palette table, laid out as a gradient (grouped by color name, groups in
    -- spectral order, shades dark -> light), aligned for readability. Each entry
    -- notes how many highlight groups use that color, and which.
    add("local p = {")
    local w = 0
    for _, hex in ipairs(ordered) do
        w = math.max(w, #var[hex])
    end
    for _, hex in ipairs(ordered) do
        local groups_using = usage[hex] or {}
        local n = #groups_using
        add(
            string.format(
                "  %-" .. w .. 's = "%s", -- %d group%s: %s',
                var[hex],
                hex,
                n,
                n == 1 and "" or "s",
                table.concat(groups_using, ", ")
            )
        )
    end
    add("}")
    add("")
    add("local set = vim.api.nvim_set_hl")

    -- One set() per group (sorted). fg/bg/sp reference palette vars.
    for _, gname in ipairs(names) do
        local def = groups[gname]
        local parts = {}
        if def.link then
            parts[#parts + 1] = string.format("link = %q", def.link)
        else
            for _, k in ipairs(HEX_KEYS) do
                if type(def[k]) == "number" then
                    parts[#parts + 1] = k .. " = p." .. var[util.hex(def[k])]
                end
            end
            for _, k in ipairs(ATTRS) do
                if def[k] ~= nil then
                    parts[#parts + 1] = k .. " = " .. tostring(def[k])
                end
            end
        end
        if #parts > 0 then
            add(string.format("set(0, %q, { %s })", gname, table.concat(parts, ", ")))
        end
    end

    return table.concat(out, "\n") .. "\n"
end

--- Write the generated colorscheme to stdpath("config")/colors/<name>.lua and
--- switch to it. With no name: if you're already on a tweaker-baked colorscheme,
--- re-bakes it in place; otherwise writes "<active colorscheme>-tweaked". Refuses
--- to overwrite an existing file unless `force` is true — except when re-baking
--- the colorscheme you're currently on (updating it in place).
---@param name string|nil
---@param force boolean|nil
---@return string|nil path
function M.write(name, force)
    -- Are we currently sitting on a colorscheme tweaker baked? (marker set by the
    -- generated file; compared to colors_name so it's ignored after switching away)
    local on_baked = vim.g.tweaker_baked ~= nil and vim.g.tweaker_baked == vim.g.colors_name

    if not name or name == "" then
        name = on_baked and vim.g.colors_name or ((vim.g.colors_name or "tweaker") .. "-tweaked")
    end
    local dir = vim.fn.stdpath("config") .. "/colors"
    local path = dir .. "/" .. name .. ".lua"

    -- Re-baking the scheme you're on updates it in place (no bang needed);
    -- overwriting any other existing file still requires the bang.
    local in_place = on_baked and name == vim.g.colors_name
    if not force and not in_place and vim.uv.fs_stat(path) then
        vim.notify(("tweaker: %s exists — use :TweakerBake! %s to overwrite"):format(path, name), vim.log.levels.WARN)
        return
    end
    vim.fn.mkdir(dir, "p")
    local f = io.open(path, "w")
    if not f then
        vim.notify("tweaker: cannot write " .. path, vim.log.levels.ERROR)
        return
    end
    f:write(M.generate(name))
    f:close()

    -- Switch to (or re-source, when re-baking in place) the freshly baked scheme.
    local ok, err = pcall(vim.cmd.colorscheme, name)
    if ok then
        vim.notify(("tweaker: baked and switched to colorscheme %q"):format(name), vim.log.levels.INFO)
    else
        vim.notify(("tweaker: baked to %s but couldn't switch: %s"):format(path, err), vim.log.levels.WARN)
    end
    return path
end

return M
