--- Live legend for tweaker-baked colorscheme files: when you open a file that
--- tweaker generated, each highlight group name in a `set(0, "Group", …)` call is
--- drawn in that group's *own* appearance, palette hex values are shown as
--- swatches, and `p.<var>` references are tinted with their color.
---
--- Everything is parsed from the file's OWN contents (its `local p = {…}` palette
--- and `set()` calls) and rendered via ephemeral highlight groups, so the preview
--- is accurate even when a different colorscheme is active. Read-only extmark
--- decoration — it never changes the buffer or your live highlights.
local M = {}

M.enabled = true

local ns = vim.api.nvim_create_namespace("tweaker.preview")

-- Boolean gui attributes we carry through from a set() call.
local ATTRS = {
    "bold",
    "italic",
    "underline",
    "undercurl",
    "underdouble",
    "underdotted",
    "underdashed",
    "strikethrough",
    "reverse",
    "standout",
    "nocombine",
    "altfont",
}

-- Ephemeral highlight groups, cached by their attribute set so identical
-- appearances share one group.
local hl_cache, hl_n = {}, 0

local function attrs_key(a)
    local keys = {}
    for k in pairs(a) do
        keys[#keys + 1] = k
    end
    table.sort(keys)
    local parts = {}
    for _, k in ipairs(keys) do
        parts[#parts + 1] = k .. "=" .. tostring(a[k])
    end
    return table.concat(parts, ",")
end

local function ephemeral(a)
    local key = attrs_key(a)
    if key == "" then
        return nil
    end
    if not hl_cache[key] then
        hl_n = hl_n + 1
        local name = "TweakerPv" .. hl_n
        pcall(vim.api.nvim_set_hl, 0, name, a)
        hl_cache[key] = name
    end
    return hl_cache[key]
end

local function swatch(hex)
    return ephemeral({ fg = hex })
end

--- Is this buffer a tweaker-generated colorscheme?
local function is_baked(buf)
    local first = vim.api.nvim_buf_get_lines(buf, 0, 1, false)[1] or ""
    return first:find("Generated by tweaker.nvim", 1, true) ~= nil
end

--- Parse the palette table and set() definitions from the file lines.
---@return table palette  var name -> "#hex"
---@return table defs     group -> { fg/bg/sp = "#hex", <attr> = true, link = "Target" }
local function parse(lines)
    local palette, defs = {}, {}
    for _, line in ipairs(lines) do
        local var, hex = line:match('^%s*([%w_]+)%s*=%s*"(#%x%x%x%x%x%x)"')
        if var and hex then
            palette[var] = hex
        end
    end
    for _, line in ipairs(lines) do
        local group, body = line:match('set%(%s*0%s*,%s*"([^"]+)"%s*,%s*(%b{})%)')
        if group and body then
            local d = {}
            local link = body:match('link%s*=%s*"([^"]+)"')
            if link then
                d.link = link
            else
                for _, k in ipairs({ "fg", "bg", "sp" }) do
                    local v = body:match(k .. "%s*=%s*p%.([%w_]+)")
                    if v and palette[v] then
                        d[k] = palette[v]
                    else
                        local lit = body:match(k .. '%s*=%s*"(#%x%x%x%x%x%x)"')
                        if lit then
                            d[k] = lit
                        end
                    end
                end
                for _, a in ipairs(ATTRS) do
                    if body:match(a .. "%s*=%s*true") then
                        d[a] = true
                    end
                end
            end
            defs[group] = d
        end
    end
    return palette, defs
end

--- Resolve a group's rendered attributes, following links within the file.
local function resolved_attrs(group, defs, seen)
    local d = defs[group]
    if not d then
        return nil
    end
    if d.link then
        seen = seen or {}
        if seen[group] then
            return nil
        end
        seen[group] = true
        return resolved_attrs(d.link, defs, seen)
    end
    local a = { fg = d.fg, bg = d.bg, sp = d.sp }
    for _, at in ipairs(ATTRS) do
        if d[at] then
            a[at] = true
        end
    end
    return a
end

local function mark(buf, row, c0, c1, hl)
    if hl and c1 > c0 then
        pcall(vim.api.nvim_buf_set_extmark, buf, ns, row, c0, { end_col = c1, hl_group = hl, priority = 200 })
    end
end

--- (Re)apply the preview decoration to a baked buffer.
function M.decorate(buf)
    if not vim.api.nvim_buf_is_valid(buf) then
        return
    end
    vim.api.nvim_buf_clear_namespace(buf, ns, 0, -1)
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    local palette, defs = parse(lines)
    for i, line in ipairs(lines) do
        local row = i - 1

        -- A 2-cell solid swatch, in the color, as virtual text right after every
        -- quoted hex value. The names/hex text themselves keep normal rendering.
        local from = 1
        while true do
            local s, e = line:find('"#%x%x%x%x%x%x"', from)
            if not s then
                break
            end
            local hex = line:sub(s + 1, e - 1)
            pcall(vim.api.nvim_buf_set_extmark, buf, ns, row, e, {
                virt_text = { { " ██", swatch(hex) } },
                virt_text_pos = "inline",
            })
            from = e + 1
        end

        -- ...and the same swatch after every p.<var> palette reference.
        from = 1
        while true do
            local s, e, v = line:find("p%.([%w_]+)", from)
            if not s then
                break
            end
            if palette[v] then
                pcall(vim.api.nvim_buf_set_extmark, buf, ns, row, e, {
                    virt_text = { { " ██", swatch(palette[v]) } },
                    virt_text_pos = "inline",
                })
            end
            from = e + 1
        end

        -- Render the group name (in set(...)) and any `link = "target"` in that
        -- group's own appearance.
        local group = line:match('set%(%s*0%s*,%s*"([^"]+)"')
        if group then
            -- Plain (literal) search — do NOT vim.pesc here: with plain=true the
            -- needle is literal, so escaping would make dotted names like
            -- "@markup.list.unchecked" search for literal "%." and never match.
            local q = line:find('"' .. group .. '"', 1, true)
            if q then
                local a = resolved_attrs(group, defs, {})
                mark(buf, row, q, q + #group, a and ephemeral(a))
            end
            local target = line:match('link%s*=%s*"([^"]+)"')
            if target then
                local li = line:find("link", 1, true) or 1
                local tq = line:find('"' .. target .. '"', li, true)
                if tq then
                    local a = resolved_attrs(target, defs, {})
                    mark(buf, row, tq, tq + #target, a and ephemeral(a))
                end
            end
        end
    end
end

--- Attach the preview to a buffer if it's a baked colorscheme (and refresh on
--- edits). Safe to call on any buffer.
function M.maybe_attach(buf)
    if not M.enabled or not vim.api.nvim_buf_is_valid(buf) or not is_baked(buf) then
        return
    end
    M.decorate(buf)
    local grp = vim.api.nvim_create_augroup("TweakerPreview_" .. buf, { clear = true })
    vim.api.nvim_create_autocmd("TextChanged", {
        group = grp,
        buffer = buf,
        callback = function()
            M.decorate(buf)
        end,
    })
end

--- Register the FileType/BufRead hook. Called from setup().
function M.setup(enabled)
    M.enabled = enabled ~= false
    if not M.enabled then
        return
    end
    vim.api.nvim_create_autocmd({ "BufReadPost", "BufWinEnter" }, {
        group = vim.api.nvim_create_augroup("TweakerPreviewDetect", { clear = true }),
        pattern = "*.lua",
        callback = function(ev)
            M.maybe_attach(ev.buf)
        end,
    })
end

return M
