describe("preview", function()
    local preview, buf, ns

    local FIXTURE = {
        '-- Generated by tweaker.nvim from the "x" colorscheme.',
        "local p = {",
        '  blue_1 = "#00aaff",',
        "}",
        "local set = vim.api.nvim_set_hl",
        'set(0, "Identifier", { fg = p.blue_1 })',
        'set(0, "@markup.list", { fg = p.blue_1 })', -- dotted name
        'set(0, "AliasGood", { link = "Identifier" })',
        'set(0, "AliasBad", { link = "NoSuchGroup" })', -- undefined target
    }

    -- fg of the highlight covering `text` on `row` (0-based), or nil.
    local function text_fg(row, text)
        for _, m in ipairs(vim.api.nvim_buf_get_extmarks(buf, ns, { row, 0 }, { row, -1 }, { details = true })) do
            local d = m[4]
            if d.hl_group and not d.virt_text then
                local covered = FIXTURE[row + 1]:sub(m[3] + 1, d.end_col)
                if covered == text then
                    return vim.api.nvim_get_hl(0, { name = d.hl_group }).fg
                end
            end
        end
    end

    -- true if any virt_text on `row` contains `needle`.
    local function has_virt(row, needle)
        for _, m in ipairs(vim.api.nvim_buf_get_extmarks(buf, ns, { row, 0 }, { row, -1 }, { details = true })) do
            local d = m[4]
            if d.virt_text then
                for _, chunk in ipairs(d.virt_text) do
                    if chunk[1]:find(needle, 1, true) then
                        return true
                    end
                end
            end
        end
        return false
    end

    before_each(function()
        package.loaded["tweaker.preview"] = nil
        preview = require("tweaker.preview")
        buf = vim.api.nvim_create_buf(false, true)
        vim.api.nvim_buf_set_lines(buf, 0, -1, false, FIXTURE)
        ns = vim.api.nvim_get_namespaces()["tweaker.preview"]
        preview.decorate(buf)
    end)

    after_each(function()
        if vim.api.nvim_buf_is_valid(buf) then
            vim.api.nvim_buf_delete(buf, { force = true })
        end
    end)

    local BLUE = tonumber("00aaff", 16)

    it("shows a color swatch after a palette hex", function()
        assert.is_true(has_virt(2, "██")) -- the blue_1 = "#00aaff" line
    end)

    it("shows a swatch after a p.<var> reference", function()
        assert.is_true(has_virt(5, "██")) -- set(0, "Identifier", { fg = p.blue_1 })
    end)

    it("renders a group name in its own color", function()
        assert.equals(BLUE, text_fg(5, "Identifier"))
    end)

    it("renders a dotted group name in its own color", function()
        assert.equals(BLUE, text_fg(6, "@markup.list"))
    end)

    it("colors a link and its target, resolving within the file", function()
        assert.equals(BLUE, text_fg(7, "AliasGood")) -- resolves through the link
        assert.equals(BLUE, text_fg(7, "Identifier")) -- the link target itself
    end)

    it("flags an undefined link target", function()
        assert.is_true(has_virt(8, "undefined link target"))
    end)

    it("toggle_swatches hides swatches but keeps the undefined marker", function()
        preview.toggle_swatches() -- refreshes all baked buffers, including this one
        assert.is_false(has_virt(2, "██"))
        assert.is_true(has_virt(8, "undefined link target"))
    end)

    it("rebuilds swatch colors after a colorscheme change wipes them", function()
        preview.setup(true) -- registers the ColorScheme handler

        local function swatch_group(row)
            for _, m in ipairs(vim.api.nvim_buf_get_extmarks(buf, ns, { row, 0 }, { row, -1 }, { details = true })) do
                local d = m[4]
                if d.virt_text then
                    for _, chunk in ipairs(d.virt_text) do
                        if chunk[1]:find("██", 1, true) and chunk[2] then
                            return chunk[2]
                        end
                    end
                end
            end
        end

        local g = swatch_group(2)
        assert.is_not_nil(g)
        assert.equals(BLUE, vim.api.nvim_get_hl(0, { name = g }).fg)

        vim.api.nvim_set_hl(0, g, {}) -- simulate `highlight clear` wiping the group
        assert.is_nil(vim.api.nvim_get_hl(0, { name = g }).fg)

        vim.api.nvim_exec_autocmds("ColorScheme", {})
        local g2 = swatch_group(2)
        assert.equals(BLUE, vim.api.nvim_get_hl(0, { name = g2 }).fg)
    end)
end)
