local util = require("tweaker.util")

describe("util", function()
    describe("hex", function()
        it("formats a 24-bit integer as #rrggbb", function()
            assert.equals("#000000", util.hex(0))
            assert.equals("#ffffff", util.hex(16777215))
            assert.equals("#ff0000", util.hex(16711680))
            assert.equals("#0078d4", util.hex(tonumber("0078d4", 16)))
        end)

        it("returns nil for non-numbers", function()
            assert.is_nil(util.hex(nil))
            assert.is_nil(util.hex("#ffffff"))
        end)
    end)

    describe("parse_color", function()
        it("accepts #rrggbb and lowercases it", function()
            assert.equals("#0078d4", util.parse_color("#0078D4"))
            assert.equals("#abcdef", util.parse_color("#abcdef"))
        end)

        it("trims surrounding whitespace", function()
            assert.equals("#ff0000", util.parse_color("  #ff0000  "))
        end)

        it("accepts NONE case-insensitively", function()
            assert.equals("NONE", util.parse_color("NONE"))
            assert.equals("NONE", util.parse_color("none"))
            assert.equals("NONE", util.parse_color("  None "))
        end)

        it("rejects invalid, partial, or empty input", function()
            assert.is_nil(util.parse_color(""))
            assert.is_nil(util.parse_color("#ff00"))
            assert.is_nil(util.parse_color("#gggggg"))
            assert.is_nil(util.parse_color("red"))
            assert.is_nil(util.parse_color(nil))
        end)
    end)

    describe("own / resolve", function()
        before_each(function()
            vim.api.nvim_set_hl(0, "TweakerTestString", { fg = tonumber("00ff00", 16) })
            vim.api.nvim_set_hl(0, "TweakerTestLink", { link = "TweakerTestString" })
        end)

        it("own returns the group's own attributes", function()
            local own = util.own("TweakerTestString")
            assert.equals(tonumber("00ff00", 16), own.fg)
            assert.is_nil(own.link)
        end)

        it("own reports a link without following it", function()
            local own = util.own("TweakerTestLink")
            assert.equals("TweakerTestString", own.link)
            assert.is_nil(own.fg)
        end)

        it("resolve follows links to the concrete color", function()
            local res = util.resolve("TweakerTestLink")
            assert.equals(tonumber("00ff00", 16), res.fg)
            assert.is_nil(res.link)
        end)

        it("returns an empty table for an unknown group", function()
            assert.are.same({}, util.own("TweakerNoSuchGroup"))
        end)
    end)
end)
